apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: ns-12
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-12
      containers:
      - name: hello-world
        image: alpine:latest
        env:
        - name: MESSAGE
          value: "Hello, World!"
        command: [ "/bin/sh" ]
        args: [ "-c", 'while true; do echo "$MESSAGE"; sleep 30; done' ]
