apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-12-ingress
  namespace: ns-12
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: dcs-12.hse.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-12-web-server
            port:
              number: 6000
