apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-12-web-server
  namespace: ns-12
  labels:
    app: app-12-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-12-web-server
  template:
    metadata:
      labels:
        app: app-12-web-server
    spec:
      containers:
      - name: web-server
        image: flensimdotcore/dcs-2025-2nd-achievement-web-server:latest
        env:
        - name: APP_SERVER_URL
          value: "http://app-12-app-server:8000"
        - name: WEB_PORT
          value: "5000"
        - name: WEB_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5000
          name: http
        # readinessProbe:
        #   httpGet:
        #     path: /health  # или /ready
        #     port: 5000
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health  # или /live
        #     port: 5000
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        # resources:
        #   requests:
        #     memory: "128Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-12-web-server
  namespace: ns-12
spec:
  selector:
    app: app-12-web-server
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP