apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-12-app-server
  namespace: ns-12
  labels:
    app: app-12-app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-12-app-server
  template:
    metadata:
      labels:
        app: app-12-app-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-12
      containers:
      - name: app-server
        image: flensimdotcore/dcs-2025-2nd-achievement-app-server:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
        - name: POSTGRES_HOST
          value: "app-12-database"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-12-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-12-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-12-secret
              key: POSTGRES_PASSWORD
        - name: APP_PORT
          value: "8000"
        - name: APP_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 8000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: app-12-app-server
  namespace: ns-12
spec:
  selector:
    app: app-12-app-server
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
